# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import pulumi
import pulumi.runtime

class GetFabricVlanResult(object):
    """
    A collection of values returned by getFabricVlan.
    """
    def __init__(__self__, id=None):
        if id and not isinstance(id, basestring):
            raise TypeError('Expected argument id to be a basestring')
        __self__.id = id
        """
        id is the provider-assigned unique ID for this managed resource.
        """

def get_fabric_vlan(description=None, name=None, vlan_id=None):
    __args__ = dict()

    __args__['description'] = description
    __args__['name'] = name
    __args__['vlanId'] = vlan_id
    __ret__ = pulumi.runtime.invoke('triton:index/getFabricVlan:getFabricVlan', __args__)

    return GetFabricVlanResult(
        id=__ret__.get('id'))
