// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";

let __config = new pulumi.Config("triton");

export let account: string = __config.require("account");
export let insecureSkipTlsVerify: boolean | undefined = __config.getObject<boolean>("insecureSkipTlsVerify");
export let keyId: string = __config.require("keyId");
export let keyMaterial: string | undefined = __config.get("keyMaterial");
export let url: string = __config.require("url");
export let user: string = __config.require("user");
