// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
	"github.com/pulumi/pulumi/sdk/go/pulumi/config"
)

func GetAccount(ctx *pulumi.Context) string {
	return config.Require(ctx, "triton:account")
}

func GetInsecureSkipTlsVerify(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "triton:insecureSkipTlsVerify")
}

func GetKeyId(ctx *pulumi.Context) string {
	return config.Require(ctx, "triton:keyId")
}

func GetKeyMaterial(ctx *pulumi.Context) string {
	return config.Get(ctx, "triton:keyMaterial")
}

func GetUrl(ctx *pulumi.Context) string {
	return config.Require(ctx, "triton:url")
}

func GetUser(ctx *pulumi.Context) string {
	return config.Require(ctx, "triton:user")
}
