// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package triton

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func LookupAccount(ctx *pulumi.Context) (*GetAccountResult, error) {
	outputs, err := ctx.Invoke("triton:index/getAccount:getAccount", nil)
	if err != nil {
		return nil, err
	}
	return &GetAccountResult{
		CnsEnabled: outputs["cnsEnabled"],
		Email: outputs["email"],
		Login: outputs["login"],
		Id: outputs["id"],
	}, nil
}

// A collection of values returned by getAccount.
type GetAccountResult struct {
	CnsEnabled interface{}
	Email interface{}
	Login interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
