// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package triton

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func LookupDatacenter(ctx *pulumi.Context) (*GetDatacenterResult, error) {
	outputs, err := ctx.Invoke("triton:index/getDatacenter:getDatacenter", nil)
	if err != nil {
		return nil, err
	}
	return &GetDatacenterResult{
		Endpoint: outputs["endpoint"],
		Name: outputs["name"],
		Id: outputs["id"],
	}, nil
}

// A collection of values returned by getDatacenter.
type GetDatacenterResult struct {
	Endpoint interface{}
	Name interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
