// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package triton

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func LookupFabricNetwork(ctx *pulumi.Context, args *GetFabricNetworkArgs) (*GetFabricNetworkResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["name"] = args.Name
		inputs["vlanId"] = args.VlanId
	}
	outputs, err := ctx.Invoke("triton:index/getFabricNetwork:getFabricNetwork", inputs)
	if err != nil {
		return nil, err
	}
	return &GetFabricNetworkResult{
		Description: outputs["description"],
		Fabric: outputs["fabric"],
		Gateway: outputs["gateway"],
		InternetNat: outputs["internetNat"],
		ProvisionEndIp: outputs["provisionEndIp"],
		ProvisionStartIp: outputs["provisionStartIp"],
		Public: outputs["public"],
		Resolvers: outputs["resolvers"],
		Routes: outputs["routes"],
		Subnet: outputs["subnet"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getFabricNetwork.
type GetFabricNetworkArgs struct {
	Name interface{}
	VlanId interface{}
}

// A collection of values returned by getFabricNetwork.
type GetFabricNetworkResult struct {
	Description interface{}
	Fabric interface{}
	Gateway interface{}
	InternetNat interface{}
	ProvisionEndIp interface{}
	ProvisionStartIp interface{}
	Public interface{}
	Resolvers interface{}
	Routes interface{}
	Subnet interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
