// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package triton

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func LookupNetwork(ctx *pulumi.Context, args *GetNetworkArgs) (*GetNetworkResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["name"] = args.Name
	}
	outputs, err := ctx.Invoke("triton:index/getNetwork:getNetwork", inputs)
	if err != nil {
		return nil, err
	}
	return &GetNetworkResult{
		Fabric: outputs["fabric"],
		Public: outputs["public"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getNetwork.
type GetNetworkArgs struct {
	Name interface{}
}

// A collection of values returned by getNetwork.
type GetNetworkResult struct {
	Fabric interface{}
	Public interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
