// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package triton

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func LookupPackage(ctx *pulumi.Context, args *GetPackageArgs) (*GetPackageResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["filters"] = args.Filters
	}
	outputs, err := ctx.Invoke("triton:index/getPackage:getPackage", inputs)
	if err != nil {
		return nil, err
	}
	return &GetPackageResult{
		Disk: outputs["disk"],
		Group: outputs["group"],
		Lwps: outputs["lwps"],
		Memory: outputs["memory"],
		Name: outputs["name"],
		Swap: outputs["swap"],
		Vcpus: outputs["vcpus"],
		Version: outputs["version"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getPackage.
type GetPackageArgs struct {
	Filters interface{}
}

// A collection of values returned by getPackage.
type GetPackageResult struct {
	Disk interface{}
	Group interface{}
	Lwps interface{}
	Memory interface{}
	Name interface{}
	Swap interface{}
	Vcpus interface{}
	Version interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
