// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package triton

import (
	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type Vlan struct {
	s *pulumi.ResourceState
}

// NewVlan registers a new resource with the given unique name, arguments, and options.
func NewVlan(ctx *pulumi.Context,
	name string, args *VlanArgs, opts ...pulumi.ResourceOpt) (*Vlan, error) {
	if args == nil || args.VlanId == nil {
		return nil, errors.New("missing required argument 'VlanId'")
	}
	inputs := make(map[string]interface{})
	if args == nil {
		inputs["description"] = nil
		inputs["name"] = nil
		inputs["vlanId"] = nil
	} else {
		inputs["description"] = args.Description
		inputs["name"] = args.Name
		inputs["vlanId"] = args.VlanId
	}
	s, err := ctx.RegisterResource("triton:index/vlan:Vlan", name, true, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &Vlan{s: s}, nil
}

// GetVlan gets an existing Vlan resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetVlan(ctx *pulumi.Context,
	name string, id pulumi.ID, state *VlanState, opts ...pulumi.ResourceOpt) (*Vlan, error) {
	inputs := make(map[string]interface{})
	if state != nil {
		inputs["description"] = state.Description
		inputs["name"] = state.Name
		inputs["vlanId"] = state.VlanId
	}
	s, err := ctx.ReadResource("triton:index/vlan:Vlan", name, id, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &Vlan{s: s}, nil
}

// URN is this resource's unique name assigned by Pulumi.
func (r *Vlan) URN() *pulumi.URNOutput {
	return r.s.URN
}

// ID is this resource's unique identifier assigned by its provider.
func (r *Vlan) ID() *pulumi.IDOutput {
	return r.s.ID
}

// Description of the VLAN
func (r *Vlan) Description() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["description"])
}

// Unique name to identify VLAN
func (r *Vlan) Name() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["name"])
}

// Number between 0-4095 indicating VLAN ID
func (r *Vlan) VlanId() *pulumi.IntOutput {
	return (*pulumi.IntOutput)(r.s.State["vlanId"])
}

// Input properties used for looking up and filtering Vlan resources.
type VlanState struct {
	// Description of the VLAN
	Description interface{}
	// Unique name to identify VLAN
	Name interface{}
	// Number between 0-4095 indicating VLAN ID
	VlanId interface{}
}

// The set of arguments for constructing a Vlan resource.
type VlanArgs struct {
	// Description of the VLAN
	Description interface{}
	// Unique name to identify VLAN
	Name interface{}
	// Number between 0-4095 indicating VLAN ID
	VlanId interface{}
}
