// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";

export class Fabric extends pulumi.CustomResource {
    /**
     * Get an existing Fabric resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: FabricState): Fabric {
        return new Fabric(name, <any>state, { id });
    }

    /**
     * Description of network
     */
    public readonly description: pulumi.Output<string | undefined>;
    /**
     * Whether or not this network is on a fabric
     */
    public /*out*/ readonly fabric: pulumi.Output<boolean>;
    /**
     * Gateway IP
     */
    public readonly gateway: pulumi.Output<string | undefined>;
    /**
     * Whether or not a NAT zone is provisioned at the Gateway IP address
     */
    public readonly internetNat: pulumi.Output<boolean | undefined>;
    /**
     * Network name
     */
    public readonly name: pulumi.Output<string>;
    /**
     * Last assignable IP on the network
     */
    public readonly provisionEndIp: pulumi.Output<string>;
    /**
     * First IP on the network that can be assigned
     */
    public readonly provisionStartIp: pulumi.Output<string>;
    /**
     * Whether or not this is an RFC1918 network
     */
    public /*out*/ readonly public: pulumi.Output<boolean>;
    /**
     * List of IP addresses for DNS resolvers
     */
    public readonly resolvers: pulumi.Output<string[]>;
    /**
     * Map of CIDR block to Gateway IP address
     */
    public readonly routes: pulumi.Output<{[key: string]: any}>;
    /**
     * CIDR formatted string describing network address space
     */
    public readonly subnet: pulumi.Output<string>;
    /**
     * VLAN on which the network exists
     */
    public readonly vlanId: pulumi.Output<number>;

    /**
     * Create a Fabric resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FabricArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: FabricArgs | FabricState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: FabricState = argsOrState as FabricState | undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["fabric"] = state ? state.fabric : undefined;
            inputs["gateway"] = state ? state.gateway : undefined;
            inputs["internetNat"] = state ? state.internetNat : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["provisionEndIp"] = state ? state.provisionEndIp : undefined;
            inputs["provisionStartIp"] = state ? state.provisionStartIp : undefined;
            inputs["public"] = state ? state.public : undefined;
            inputs["resolvers"] = state ? state.resolvers : undefined;
            inputs["routes"] = state ? state.routes : undefined;
            inputs["subnet"] = state ? state.subnet : undefined;
            inputs["vlanId"] = state ? state.vlanId : undefined;
        } else {
            const args = argsOrState as FabricArgs | undefined;
            if (!args || args.provisionEndIp === undefined) {
                throw new Error("Missing required property 'provisionEndIp'");
            }
            if (!args || args.provisionStartIp === undefined) {
                throw new Error("Missing required property 'provisionStartIp'");
            }
            if (!args || args.subnet === undefined) {
                throw new Error("Missing required property 'subnet'");
            }
            if (!args || args.vlanId === undefined) {
                throw new Error("Missing required property 'vlanId'");
            }
            inputs["description"] = args ? args.description : undefined;
            inputs["gateway"] = args ? args.gateway : undefined;
            inputs["internetNat"] = args ? args.internetNat : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["provisionEndIp"] = args ? args.provisionEndIp : undefined;
            inputs["provisionStartIp"] = args ? args.provisionStartIp : undefined;
            inputs["resolvers"] = args ? args.resolvers : undefined;
            inputs["routes"] = args ? args.routes : undefined;
            inputs["subnet"] = args ? args.subnet : undefined;
            inputs["vlanId"] = args ? args.vlanId : undefined;
            inputs["fabric"] = undefined /*out*/;
            inputs["public"] = undefined /*out*/;
        }
        super("triton:index/fabric:Fabric", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Fabric resources.
 */
export interface FabricState {
    /**
     * Description of network
     */
    readonly description?: pulumi.Input<string>;
    /**
     * Whether or not this network is on a fabric
     */
    readonly fabric?: pulumi.Input<boolean>;
    /**
     * Gateway IP
     */
    readonly gateway?: pulumi.Input<string>;
    /**
     * Whether or not a NAT zone is provisioned at the Gateway IP address
     */
    readonly internetNat?: pulumi.Input<boolean>;
    /**
     * Network name
     */
    readonly name?: pulumi.Input<string>;
    /**
     * Last assignable IP on the network
     */
    readonly provisionEndIp?: pulumi.Input<string>;
    /**
     * First IP on the network that can be assigned
     */
    readonly provisionStartIp?: pulumi.Input<string>;
    /**
     * Whether or not this is an RFC1918 network
     */
    readonly public?: pulumi.Input<boolean>;
    /**
     * List of IP addresses for DNS resolvers
     */
    readonly resolvers?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Map of CIDR block to Gateway IP address
     */
    readonly routes?: pulumi.Input<{[key: string]: any}>;
    /**
     * CIDR formatted string describing network address space
     */
    readonly subnet?: pulumi.Input<string>;
    /**
     * VLAN on which the network exists
     */
    readonly vlanId?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a Fabric resource.
 */
export interface FabricArgs {
    /**
     * Description of network
     */
    readonly description?: pulumi.Input<string>;
    /**
     * Gateway IP
     */
    readonly gateway?: pulumi.Input<string>;
    /**
     * Whether or not a NAT zone is provisioned at the Gateway IP address
     */
    readonly internetNat?: pulumi.Input<boolean>;
    /**
     * Network name
     */
    readonly name?: pulumi.Input<string>;
    /**
     * Last assignable IP on the network
     */
    readonly provisionEndIp: pulumi.Input<string>;
    /**
     * First IP on the network that can be assigned
     */
    readonly provisionStartIp: pulumi.Input<string>;
    /**
     * List of IP addresses for DNS resolvers
     */
    readonly resolvers?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Map of CIDR block to Gateway IP address
     */
    readonly routes?: pulumi.Input<{[key: string]: any}>;
    /**
     * CIDR formatted string describing network address space
     */
    readonly subnet: pulumi.Input<string>;
    /**
     * VLAN on which the network exists
     */
    readonly vlanId: pulumi.Input<number>;
}
