// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";

export function getAccount(opts?: pulumi.InvokeOptions): Promise<GetAccountResult> {
    return pulumi.runtime.invoke("triton:index/getAccount:getAccount", {
    }, opts);
}

/**
 * A collection of values returned by getAccount.
 */
export interface GetAccountResult {
    readonly cnsEnabled: boolean;
    readonly email: string;
    readonly login: string;
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
