// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";

export function getFabricVlan(args?: GetFabricVlanArgs, opts?: pulumi.InvokeOptions): Promise<GetFabricVlanResult> {
    args = args || {};
    return pulumi.runtime.invoke("triton:index/getFabricVlan:getFabricVlan", {
        "description": args.description,
        "name": args.name,
        "vlanId": args.vlanId,
    }, opts);
}

/**
 * A collection of arguments for invoking getFabricVlan.
 */
export interface GetFabricVlanArgs {
    readonly description?: string;
    readonly name?: string;
    readonly vlanId?: number;
}

/**
 * A collection of values returned by getFabricVlan.
 */
export interface GetFabricVlanResult {
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
