// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";

export function getFabricNetwork(args: GetFabricNetworkArgs, opts?: pulumi.InvokeOptions): Promise<GetFabricNetworkResult> {
    return pulumi.runtime.invoke("triton:index/getFabricNetwork:getFabricNetwork", {
        "name": args.name,
        "vlanId": args.vlanId,
    }, opts);
}

/**
 * A collection of arguments for invoking getFabricNetwork.
 */
export interface GetFabricNetworkArgs {
    readonly name: string;
    readonly vlanId: number;
}

/**
 * A collection of values returned by getFabricNetwork.
 */
export interface GetFabricNetworkResult {
    readonly description: string;
    readonly fabric: boolean;
    readonly gateway: string;
    readonly internetNat: boolean;
    readonly provisionEndIp: string;
    readonly provisionStartIp: string;
    readonly public: boolean;
    readonly resolvers: string[];
    readonly routes: {[key: string]: string};
    readonly subnet: string;
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
