// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";

export function getImage(args?: GetImageArgs, opts?: pulumi.InvokeOptions): Promise<GetImageResult> {
    args = args || {};
    return pulumi.runtime.invoke("triton:index/getImage:getImage", {
        "mostRecent": args.mostRecent,
        "name": args.name,
        "os": args.os,
        "owner": args.owner,
        "public": args.public,
        "state": args.state,
        "type": args.type,
        "version": args.version,
    }, opts);
}

/**
 * A collection of arguments for invoking getImage.
 */
export interface GetImageArgs {
    readonly mostRecent?: boolean;
    readonly name?: string;
    readonly os?: string;
    readonly owner?: string;
    readonly public?: boolean;
    readonly state?: string;
    readonly type?: string;
    readonly version?: string;
}

/**
 * A collection of values returned by getImage.
 */
export interface GetImageResult {
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
