// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";

/**
 * The provider type for the triton package
 */
export class Provider extends pulumi.ProviderResource {

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let inputs: pulumi.Inputs = {};
        {
            if (!args || args.account === undefined) {
                throw new Error("Missing required property 'account'");
            }
            if (!args || args.keyId === undefined) {
                throw new Error("Missing required property 'keyId'");
            }
            if (!args || args.url === undefined) {
                throw new Error("Missing required property 'url'");
            }
            if (!args || args.user === undefined) {
                throw new Error("Missing required property 'user'");
            }
            inputs["account"] = args ? args.account : undefined;
            inputs["insecureSkipTlsVerify"] = args ? args.insecureSkipTlsVerify : undefined;
            inputs["keyId"] = args ? args.keyId : undefined;
            inputs["keyMaterial"] = args ? args.keyMaterial : undefined;
            inputs["url"] = args ? args.url : undefined;
            inputs["user"] = args ? args.user : undefined;
        }
        super("triton", name, inputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    readonly account: pulumi.Input<string>;
    readonly insecureSkipTlsVerify?: pulumi.Input<boolean>;
    readonly keyId: pulumi.Input<string>;
    readonly keyMaterial?: pulumi.Input<string>;
    readonly url: pulumi.Input<string>;
    readonly user: pulumi.Input<string>;
}
